[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mdi-llmkit"
version = "1.0.3"
description = "Utilities for managing multi-shot conversations and structured data handling in LLM applications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "python-dotenv>=1.0.1",
  "openai>=2.24.0",
]
authors = [{ name = "Mikhail Voloshin" }]
license = { file = "LICENSE" }

[tool.hatch.build.targets.wheel]
packages = ["src/mdi_llmkit"]
